apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-ingress-tls
  dnsNames:
    - argocd.lab.amirbeile.uk
  issuerRef:
    name: issuer
    kind: ClusterIssuer
  duration: 90d
  renewBefore: 30d
