apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-app
  labels:
    app: detect-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detect-app
  template:
    metadata:
      labels:
        app: detect-app
    spec:
      containers:
        - name: detect-app
          image: 872515255126.dkr.ecr.eu-west-2.amazonaws.com/detect-app
          ports:
          - containerPort: 3000
          volumeMounts:
            - name: local-pvc
              mountPath: /app/tmp
      volumes:
        - name: local-pvc
          persistentVolumeClaim:
          claimName: local-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: detect-app-service
spec:
  selector:
    app: detect-app
  type: ClusterIP
  ports:
    - name: http
    - protocol: TCP
      port: 3000
      targetPort: 3000


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: detect-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "issuer"
spec:
  ingressClassName: nginx
  rules:
    - host: detect-app.lab.amirbeile.uk
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: detect-app-service
              port:
                number: 3000
  tls:
  - hosts:
    - detect-app.lab.amirbeile.uk
    secretName: detect-app-tls