alertmanager:
  alertmanagerSpec:
    env:
      - name: SLACK_WEBHOOK_URL
        valueFrom:
          secretKeyRef:
            name: alertmanager-slack-secret
            key: slack_webhook_url

    config:
      global:
        resolve_timeout: 5m
      route:
        receiver: 'slack-notifications'
      receivers:
        - name: 'slack-notifications'
          slack_configs:
            - send_resolved: true
              text: "{{ .CommonAnnotations.summary }}"
              api_url: "http://${SLACK_WEBHOOK_URL}"
              
              
# 'https://hooks.slack.com/services/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'